#!/bin/sh

cat <<EOF > activate_aiocells
# =============================================================================
# Generated by $(basename $0)
# =============================================================================

. .config/py37/bin/activate

# Add table completion for 'aiocells' command

eval "\$(_AIOCELLS_COMPLETE=source_bash aiocells)"

EOF
