#!/bin/sh

set -e
set -u

if [ $# != 1 ]; then
    echo usage: $(basename $0) "<virtual env dir>"
    exit 1
fi

venv=${1}

cat <<EOF > activate_aiocells
# =============================================================================
# Generated by $(basename $0)
# =============================================================================

. ${venv}/bin/activate

# Add table completion for 'aiocells' command

eval "\$(_AIOCELLS_COMPLETE=source_bash aiocells)"

EOF
