#!/bin/sh

cat<<EOF

This script is used to set up a virtual environment for you. A virtual
environment is recommended because, for development, the package will be
installed using "pip install --editable" to make the scripts available from the
command line.

Below, you may decline to have this script generate the virtual environment.
However, the use of "pip install" mentioned just above may fail.

EOF

read -p "Would you like to set up a virtual environment? [Yn] " want_venv

if [ "${want_venv}" = n ]; then
    > .venv_initialised
    exit 0
fi

if ! which virtualenv; then
    cat<<EOF
virtualenv command not found. Is it installed?
It can be installed witht the following command:

  $ pip install --user virtualenv

EOF
fi

which_virtualenv=$(which virtualenv)

old_virtual_env_error() {
    cat<<EOF
virtualenv must be at least version 20. It is $(virtualenv --version)

It can be installed with the following command:

  $ pip install --user virtualenv

The directory ~/.local/bin must be in your PATH for this work. You
may have to kill the current shell also in case the path to the
old version has been cached.
EOF

    exit 1
}

# We're expecting a version format of 'virtualenv A.B.C from ....'
# Older versions do not have this format.
if ! $(virtualenv --version | grep -q '^virtualenv'); then
    old_virtual_env_error
fi

# Extract the major version
virtual_env_major_version=$(virtualenv --version  | awk '{print $2}' | awk -F. '{print $1}')

if [ "${virtual_env_major_version}" -lt 20 ]; then
    old_virtual_env_error
fi

virtualenv -p 3.7 .venv

cat <<EOF > activate_aiocells
. .venv/bin/activate

eval "\$(_AIOCELLS_COMPLETE=source_bash aiocells)"
EOF

> .venv_initialised

cat<<EOF

A script 'activate_aiocells' has been created in this directory. To activate
the virtual environment:

  $ source activate_aiocells

EOF
